#include "unittable.h"


std::vector<std::pair<std::string, int>> CSpriteFields = {
    {"prev", 4},
    {"next", 4},
    {"spriteID", 4},
    {"playerID", 4},
    {"selectionIndex", 1},
    {"visibilityFlags", 1},
    {"elevationLevel", 1},
    {"flags", 1},
    {"selectionTimer", 1},
    {"index", 2},
    {"grpWidth", 1},
    {"grpHeight", 1},
    {"posX", 2},
    {"posY", 2},
    {"mainGraphic", 4},
    {"imageHead", 4},
    {"imageTail", 4}};

// CUnit field sizes
std::vector<std::pair<std::string, int>> CUnitFields = {
    {"prev", 4},
    {"next", 4},
    {"hp", 4},
    {"sprite", 4},
    {"moveTargetX", 2},
    {"moveTargetY", 2},
    {"moveTarget", 4},
    {"nextMovementWaypoint", 4},
    {"nextTargetWaypoint", 4},
    {"movementFlags", 1},
    {"currentDirection1", 1},
    {"flingyTurnRadius", 1},
    {"velocityDirection1", 1},
    {"flingyID", 2},
    {"unknown0x26", 1},
    {"flingyMovementType", 1},
    {"posX", 2},
    {"posY", 2},
    {"haltX", 4},
    {"haltY", 4},
    {"topSpeed", 4},
    {"currentSpeed1", 4},
    {"currentSpeed2", 4},
    {"currentVelocityX", 4},
    {"currentVelocityY", 4},
    {"acceleration", 2},
    {"currentDirection2", 1},
    {"velocityDirection2", 1},
    {"playerID", 1},
    {"orderID", 1},
    {"orderState", 1},
    {"orderSignal", 1},
    {"orderUnitType", 2},
    {"unknown16_52", 2},
    {"orderTimer", 1},
    {"groundWeaponCooldown", 1},
    {"airWeaponCooldown", 1},
    {"spellCooldown", 1},
    {"orderTargetX", 2},
    {"orderTargetY", 2},
    {"orderTarget", 4},
    {"shield", 4},
    {"unitID", 2},
    {"unknown0x66", 2},
    {"prevPlayerUnit", 4},
    {"nextPlayerUnit", 4},
    {"subUnit", 4},
    {"orderQueueHead", 4},
    {"orderQueueTail", 4},
    {"autoTargetUnit", 4},
    {"connectedUnit", 4},
    {"orderQueueCount", 1},
    {"orderQueueTimer", 1},
    {"unknown0x86", 1},
    {"attackNotifyTimer", 1},
    {"prevUnitType", 2},
    {"lastEventTimer", 1},
    {"lastEventColor", 1},
    {"unknown16_8C", 2},
    {"rankIncrease", 1},
    {"killCount", 1},
    {"lastAttackingPlayer", 1},
    {"secondaryOrderTimer", 1},
    {"AIActionFlag", 1},
    {"userActionFlags", 1},
    {"currentButtonSet", 2},
    {"isCloaked", 1},
    {"movementState", 1},
    {"buildQueue1", 2},
    {"buildQueue2", 2},
    {"buildQueue3", 2},
    {"buildQueue4", 2},
    {"buildQueue5", 2},
    {"energy", 2},
    {"buildQueueSlot", 1},
    {"uniquenessIdentifier", 1},
    {"secondaryOrderID", 1},
    {"buildingOverlayState", 1},
    {"hpGain", 2},
    {"shieldGain", 2},
    {"remainingBuildTime", 2},
    {"prevHp", 2},
    {"loadedUnit1", 2},
    {"loadedUnit2", 2},
    {"loadedUnit3", 2},
    {"loadedUnit4", 2},
    {"loadedUnit5", 2},
    {"loadedUnit6", 2},
    {"loadedUnit7", 2},
    {"loadedUnit8", 2},
    {"addon", 4},
    {"addonBuildType", 4},
    {"upgradeResearchTime", 2},
    {"abilityID", 4},
    {"soundIndex", 4},
    {"buildAngle", 4},
    {"unknown0xD8", 4},
    {"statusFlag", 4},
    {"owningOreType", 1},
    {"wireframeRandomizer", 1},
    {"secondaryOrderState", 1},
    {"recentOrderTimer", 1},
    {"visibilityStatus", 4},
    {"secondaryOrderPosition", 4},
    {"currentBuildUnit", 4},
    {"previousBurrowedUnit", 4},
    {"nextBurrowedUnit", 4},
    {"RallyX", 2},
    {"RallyY", 2},
    {"RallyUnit", 4},
    {"dwPath", 4},
    {"pathingCollisionInterval", 1},
    {"pathingFlags", 1},
    {"unknown8_106", 1},
    {"isBeingHealed", 1},
    {"unknown32_108", 4},
    {"unknown32_10C", 4},
    {"removeTimer", 2},
    {"defenseMatrixDamage", 2},
    {"defenseMatrixTimer", 1},
    {"stimTimer", 1},
    {"ensnareTimer", 1},
    {"lockdownTimer", 1},
    {"irradiateTimer", 1},
    {"stasisTimer", 1},
    {"plagueTimer", 1},
    {"stormTimer", 1},
    {"irradiatedBy", 4},
    {"irradiatePlayerID", 1},
    {"parasiteFlags", 1},
    {"cycleCounter", 1},
    {"isBlind", 1},
    {"maelstromTimer", 1},
    {"empty8_125", 1},
    {"acidSporeCount", 1},
    {"acidSporeTime0", 1},
    {"acidSporeTime1", 1},
    {"acidSporeTime2", 1},
    {"acidSporeTime3", 1},
    {"acidSporeTime4", 1},
    {"acidSporeTime5", 1},
    {"acidSporeTime6", 1},
    {"acidSporeTime7", 1},
    {"acidSporeTime8", 1},
    {"bullet3Attack", 2},
    {"padding_132", 2},
    {"pAI", 4},
    {"airStrength", 2},
    {"groundStrength", 2},
    {"posSortXL", 4},
    {"posSortXR", 4},
    {"posSortYT", 4},
    {"posSortYB", 4},
    {"_repulseUnknown", 1},
    {"repulseAngle", 1},
    {"bRepMtxX", 1},
    {"bRepMtxY", 1}};

std::unordered_map<std::string, int> UnitField = {
    {"Terran Marine", 0},
    {"Terran Ghost", 1},
    {"Terran Vulture", 2},
    {"Terran Goliath", 3},
    {"Goliath Turret", 4},
    {"Terran Siege Tank (Tank Mode)", 5},
    {"Siege Tank Turret (Tank Mode)", 6},
    {"Tank Turret type   1", 6},
    {"Terran SCV", 7},
    {"Terran Wraith", 8},
    {"Terran Science Vessel", 9},
    {"Gui Montag (Firebat)", 10},
    {"Terran Dropship", 11},
    {"Terran Battlecruiser", 12},
    {"Spider Mine", 13},
    {"Vulture Spider Mine", 13},
    {"Nuclear Missile", 14},
    {"Terran Civilian", 15},
    {"Sarah Kerrigan (Ghost)", 16},
    {"Alan Schezar (Goliath)", 17},
    {"Alan Schezar Turret", 18},
    {"Alan Turret", 18},
    {"Jim Raynor (Vulture)", 19},
    {"Jim Raynor (Marine)", 20},
    {"Tom Kazansky (Wraith)", 21},
    {"Magellan (Science Vessel)", 22},
    {"Edmund Duke (Tank Mode)", 23},
    {"Edmund Duke (Siege Tank)", 23},
    {"Edmund Duke Turret (Tank Mode)", 24},
    {"Duke Turret type   1", 24},
    {"Edmund Duke (Siege Mode)", 25},
    {"Edmund Duke Turret (Siege Mode)", 26},
    {"Duke Turret type   2", 26},
    {"Arcturus Mengsk (Battlecruiser)", 27},
    {"Hyperion (Battlecruiser)", 28},
    {"Norad II (Battlecruiser)", 29},
    {"Terran Siege Tank (Siege Mode)", 30},
    {"Siege Tank Turret (Siege Mode)", 31},
    {"Tank Turret type   2", 31},
    {"Terran Firebat", 32},
    {"Scanner Sweep", 33},
    {"Terran Medic", 34},
    {"Zerg Larva", 35},
    {"Zerg Egg", 36},
    {"Zerg Zergling", 37},
    {"Zerg Hydralisk", 38},
    {"Zerg Ultralisk", 39},
    {"Zerg Broodling", 40},
    {"Zerg Drone", 41},
    {"Zerg Overlord", 42},
    {"Zerg Mutalisk", 43},
    {"Zerg Guardian", 44},
    {"Zerg Queen", 45},
    {"Zerg Defiler", 46},
    {"Zerg Scourge", 47},
    {"Torrasque (Ultralisk)", 48},
    {"Matriarch (Queen)", 49},
    {"Infested Terran", 50},
    {"Infested Kerrigan (Infested Terran)", 51},
    {"Unclean One (Defiler)", 52},
    {"Hunter Killer (Hydralisk)", 53},
    {"Devouring One (Zergling)", 54},
    {"Kukulza (Mutalisk)", 55},
    {"Kukulza (Guardian)", 56},
    {"Yggdrasill (Overlord)", 57},
    {"Terran Valkyrie", 58},
    {"Mutalisk Cocoon", 59},
    {"Cocoon", 59},
    {"Protoss Corsair", 60},
    {"Protoss Dark Templar (Unit)", 61},
    {"Protoss Dark Templar", 61},
    {"Zerg Devourer", 62},
    {"Protoss Dark Archon", 63},
    {"Protoss Probe", 64},
    {"Protoss Zealot", 65},
    {"Protoss Dragoon", 66},
    {"Protoss High Templar", 67},
    {"Protoss Archon", 68},
    {"Protoss Shuttle", 69},
    {"Protoss Scout", 70},
    {"Protoss Arbiter", 71},
    {"Protoss Carrier", 72},
    {"Protoss Interceptor", 73},
    {"Protoss Dark Templar (Hero)", 74},
    {"Dark Templar (Hero)", 74},
    {"Zeratul (Dark Templar)", 75},
    {"Tassadar/Zeratul (Archon)", 76},
    {"Fenix (Zealot)", 77},
    {"Fenix (Dragoon)", 78},
    {"Tassadar (Templar)", 79},
    {"Mojo (Scout)", 80},
    {"Warbringer (Reaver)", 81},
    {"Gantrithor (Carrier)", 82},
    {"Protoss Reaver", 83},
    {"Protoss Observer", 84},
    {"Protoss Scarab", 85},
    {"Danimoth (Arbiter)", 86},
    {"Aldaris (Templar)", 87},
    {"Artanis (Scout)", 88},
    {"Rhynadon (Badlands Critter)", 89},
    {"Bengalaas (Jungle Critter)", 90},
    {"Cargo Ship (Unused)", 91},
    {"Mercenary Gunship (Unused)", 92},
    {"Scantid (Desert Critter)", 93},
    {"Kakaru (Twilight Critter)", 94},
    {"Ragnasaur (Ashworld Critter)", 95},
    {"Ursadon (Ice World Critter)", 96},
    {"Rhynadon (Badlands)", 89},
    {"Bengalaas (Jungle)", 90},
    {"Cargo Ship (Unused)", 91},
    {"Unused type   1", 91},
    {"Unused type   2", 92},
    {"Scantid (Desert)", 93},
    {"Kakaru (Twilight)", 94},
    {"Ragnasaur (Ashworld)", 95},
    {"Ursadon (Ice World)", 96},
    {"Lurker Egg", 97},
    {"Raszagal (Corsair)", 98},
    {"Samir Duran (Ghost)", 99},
    {"Alexei Stukov (Ghost)", 100},
    {"Map Revealer", 101},
    {"Gerard DuGalle (BattleCruiser)", 102},
    {"Gerard DuGalle (Ghost)", 102},
    {"Zerg Lurker", 103},
    {"Infested Duran (Infested Terran)", 104},
    {"Infested Duran", 104},
    {"Disruption Web", 105},
    {"Disruption Field", 105},
    {"Terran Command Center", 106},
    {"Terran Comsat Station", 107},
    {"Terran Nuclear Silo", 108},
    {"Terran Supply Depot", 109},
    {"Terran Refinery", 110},
    {"Terran Barracks", 111},
    {"Terran Academy", 112},
    {"Terran Factory", 113},
    {"Terran Starport", 114},
    {"Terran Control Tower", 115},
    {"Terran Science Facility", 116},
    {"Terran Covert Ops", 117},
    {"Terran Physics Lab", 118},
    {"Starbase (Unused)", 119},
    {"Unused Terran Bldg type   1", 119},
    {"Terran Machine Shop", 120},
    {"Repair Bay (Unused)", 121},
    {"Unused Terran Bldg type   2", 121},
    {"Terran Engineering Bay", 122},
    {"Terran Armory", 123},
    {"Terran Missile Turret", 124},
    {"Terran Bunker", 125},
    {"Norad II (Crashed)", 126},
    {"Norad II (Crashed Battlecruiser)", 126},
    {"Ion Cannon", 127},
    {"Uraj Crystal", 128},
    {"Khalis Crystal", 129},
    {"Infested Command Center", 130},
    {"Zerg Hatchery", 131},
    {"Zerg Lair", 132},
    {"Zerg Hive", 133},
    {"Zerg Nydus Canal", 134},
    {"Zerg Hydralisk Den", 135},
    {"Zerg Defiler Mound", 136},
    {"Zerg Greater Spire", 137},
    {"Zerg Queen's Nest", 138},
    {"Zerg Evolution Chamber", 139},
    {"Zerg Ultralisk Cavern", 140},
    {"Zerg Spire", 141},
    {"Zerg Spawning Pool", 142},
    {"Zerg Creep Colony", 143},
    {"Zerg Spore Colony", 144},
    {"Unused Zerg Building1", 145},
    {"Unused Zerg Bldg", 145},
    {"Zerg Sunken Colony", 146},
    {"Zerg Overmind (With Shell)", 147},
    {"Zerg Overmind", 148},
    {"Zerg Extractor", 149},
    {"Mature Chrysalis", 150},
    {"Mature Crysalis", 150},
    {"Zerg Cerebrate", 151},
    {"Zerg Cerebrate Daggoth", 152},
    {"Unused Zerg Building2", 153},
    {"Protoss Nexus", 154},
    {"Protoss Robotics Facility", 155},
    {"Protoss Pylon", 156},
    {"Protoss Assimilator", 157},
    {"Protoss Unused type   1", 157},
    {"Unused Protoss Building1", 158},
    {"Protoss Observatory", 159},
    {"Protoss Gateway", 160},
    {"Unused Protoss Building2", 161},
    {"Protoss Unused type   2", 161},
    {"Protoss Photon Cannon", 162},
    {"Protoss Citadel of Adun", 163},
    {"Protoss Cybernetics Core", 164},
    {"Protoss Templar Archives", 165},
    {"Protoss Forge", 166},
    {"Protoss Stargate", 167},
    {"Stasis Cell/Prison", 168},
    {"Protoss Fleet Beacon", 169},
    {"Protoss Arbiter Tribunal", 170},
    {"Protoss Robotics Support Bay", 171},
    {"Protoss Shield Battery", 172},
    {"Khaydarin Crystal Formation", 173},
    {"Protoss Temple", 174},
    {"Xel'Naga Temple", 175},
    {"Mineral Field (Type 1)", 176},
    {"Mineral Field (Type 2)", 177},
    {"Mineral Field (Type 3)", 178},
    {"Cave (Unused)", 179},
    {"Cave-in (Unused)", 180},
    {"Cantina (Unused)", 181},
    {"Mining Platform (Unused)", 182},
    {"Independent Command Center (Unused)", 183},
    {"Independent Starport (Unused)", 184},
    {"Independent Jump Gate (Unused)", 185},
    {"Ruins (Unused)", 186},
    {"Khaydarin Crystal Formation (Unused)", 187},
    {"Cave", 179},
    {"Cave-in", 180},
    {"Cantina", 181},
    {"Mining Platform", 182},
    {"Independent Command Center", 183},
    {"Independent Starport", 184},
    {"Jump Gate", 185},
    {"Ruins", 186},
    {"Kyadarin Crystal Formation", 187},
    {"Vespene Geyser", 188},
    {"Warp Gate", 189},
    {"Psi Disrupter", 190},
    {"Zerg Marker", 191},
    {"Terran Marker", 192},
    {"Protoss Marker", 193},
    {"Zerg Beacon", 194},
    {"Terran Beacon", 195},
    {"Protoss Beacon", 196},
    {"Zerg Flag Beacon", 197},
    {"Terran Flag Beacon", 198},
    {"Protoss Flag Beacon", 199},
    {"Power Generator", 200},
    {"Overmind Cocoon", 201},
    {"Dark Swarm", 202},
    {"Floor Missile Trap", 203},
    {"Floor Hatch (Unused)", 204},
    {"Floor Hatch (UNUSED)", 204},
    {"Left Upper Level Door", 205},
    {"Right Upper Level Door", 206},
    {"Left Pit Door", 207},
    {"Right Pit Door", 208},
    {"Floor Gun Trap", 209},
    {"Left Wall Missile Trap", 210},
    {"Left Wall Flame Trap", 211},
    {"Right Wall Missile Trap", 212},
    {"Right Wall Flame Trap", 213},
    {"Start Location", 214},
    {"Flag", 215},
    {"Young Chrysalis", 216},
    {"Psi Emitter", 217},
    {"Data Disc", 218},
    {"Khaydarin Crystal", 219},
    {"Mineral Cluster Type 1", 220},
    {"Mineral Cluster Type 2", 221},
    {"Protoss Vespene Gas Orb Type 1", 222},
    {"Protoss Vespene Gas Orb Type 2", 223},
    {"Zerg Vespene Gas Sac Type 1", 224},
    {"Zerg Vespene Gas Sac Type 2", 225},
    {"Terran Vespene Gas Tank Type 1", 226},
    {"Terran Vespene Gas Tank Type 2", 227},
    {"(any unit)", 229},
    {"(men)", 230},
    {"(buildings)", 231},
    {"(factories)", 232},
    {"Mineral Chunk (Type 1)", 220},
    {"Mineral Chunk (Type 2)", 221},
    {"Vespene Orb (Protoss Type 1)", 222},
    {"Vespene Orb (Protoss Type 2)", 223},
    {"Vespene Sac (Zerg Type 1)", 224},
    {"Vespene Sac (Zerg Type 2)", 225},
    {"Vespene Tank (Terran Type 1)", 226},
    {"Vespene Tank (Terran Type 2)", 227},
    {"Unused unit 228", 228},
    {"Any unit", 229},
    {"Men", 230},
    {"Buildings", 231},
    {"Factories", 232},
};

std::unordered_map<int, std::string> UnitDict = {
    {0, "Terran Marine"},
    {1, "Terran Ghost"},
    {2, "Terran Vulture"},
    {3, "Terran Goliath"},
    {4, "Goliath Turret"},
    {5, "Terran Siege Tank (Tank Mode)"},
    {6, "Siege Tank Turret (Tank Mode)"},
    {7, "Terran SCV"},
    {8, "Terran Wraith"},
    {9, "Terran Science Vessel"},
    {10, "Gui Montag (Firebat)"},
    {11, "Terran Dropship"},
    {12, "Terran Battlecruiser"},
    {13, "Spider Mine"},
    {14, "Nuclear Missile"},
    {15, "Terran Civilian"},
    {16, "Sarah Kerrigan (Ghost)"},
    {17, "Alan Schezar (Goliath)"},
    {18, "Alan Schezar Turret"},
    {19, "Jim Raynor (Vulture)"},
    {20, "Jim Raynor (Marine)"},
    {21, "Tom Kazansky (Wraith)"},
    {22, "Magellan (Science Vessel)"},
    {23, "Edmund Duke (Tank Mode)"},
    {24, "Edmund Duke Turret (Tank Mode)"},
    {25, "Edmund Duke (Siege Mode)"},
    {26, "Edmund Duke Turret (Siege Mode)"},
    {27, "Arcturus Mengsk (Battlecruiser)"},
    {28, "Hyperion (Battlecruiser)"},
    {29, "Norad II (Battlecruiser)"},
    {30, "Terran Siege Tank (Siege Mode)"},
    {31, "Siege Tank Turret (Siege Mode)"},
    {32, "Terran Firebat"},
    {33, "Scanner Sweep"},
    {34, "Terran Medic"},
    {35, "Zerg Larva"},
    {36, "Zerg Egg"},
    {37, "Zerg Zergling"},
    {38, "Zerg Hydralisk"},
    {39, "Zerg Ultralisk"},
    {40, "Zerg Broodling"},
    {41, "Zerg Drone"},
    {42, "Zerg Overlord"},
    {43, "Zerg Mutalisk"},
    {44, "Zerg Guardian"},
    {45, "Zerg Queen"},
    {46, "Zerg Defiler"},
    {47, "Zerg Scourge"},
    {48, "Torrasque (Ultralisk)"},
    {49, "Matriarch (Queen)"},
    {50, "Infested Terran"},
    {51, "Infested Kerrigan (Infested Terran)"},
    {52, "Unclean One (Defiler)"},
    {53, "Hunter Killer (Hydralisk)"},
    {54, "Devouring One (Zergling)"},
    {55, "Kukulza (Mutalisk)"},
    {56, "Kukulza (Guardian)"},
    {57, "Yggdrasill (Overlord)"},
    {58, "Terran Valkyrie"},
    {59, "Mutalisk Cocoon"},
    {60, "Protoss Corsair"},
    {61, "Protoss Dark Templar (Unit)"},
    {62, "Zerg Devourer"},
    {63, "Protoss Dark Archon"},
    {64, "Protoss Probe"},
    {65, "Protoss Zealot"},
    {66, "Protoss Dragoon"},
    {67, "Protoss High Templar"},
    {68, "Protoss Archon"},
    {69, "Protoss Shuttle"},
    {70, "Protoss Scout"},
    {71, "Protoss Arbiter"},
    {72, "Protoss Carrier"},
    {73, "Protoss Interceptor"},
    {74, "Protoss Dark Templar (Hero)"},
    {75, "Zeratul (Dark Templar)"},
    {76, "Tassadar/Zeratul (Archon)"},
    {77, "Fenix (Zealot)"},
    {78, "Fenix (Dragoon)"},
    {79, "Tassadar (Templar)"},
    {80, "Mojo (Scout)"},
    {81, "Warbringer (Reaver)"},
    {82, "Gantrithor (Carrier)"},
    {83, "Protoss Reaver"},
    {84, "Protoss Observer"},
    {85, "Protoss Scarab"},
    {86, "Danimoth (Arbiter)"},
    {87, "Aldaris (Templar)"},
    {88, "Artanis (Scout)"},
    {89, "Rhynadon (Badlands Critter)"},
    {90, "Bengalaas (Jungle Critter)"},
    {91, "Cargo Ship (Unused)"},
    {92, "Mercenary Gunship (Unused)"},
    {93, "Scantid (Desert Critter)"},
    {94, "Kakaru (Twilight Critter)"},
    {95, "Ragnasaur (Ashworld Critter)"},
    {96, "Ursadon (Ice World Critter)"},
    {97, "Lurker Egg"},
    {98, "Raszagal (Corsair)"},
    {99, "Samir Duran (Ghost)"},
    {100, "Alexei Stukov (Ghost)"},
    {101, "Map Revealer"},
    {102, "Gerard DuGalle (BattleCruiser)"},
    {103, "Zerg Lurker"},
    {104, "Infested Duran (Infested Terran)"},
    {105, "Disruption Web"},
    {106, "Terran Command Center"},
    {107, "Terran Comsat Station"},
    {108, "Terran Nuclear Silo"},
    {109, "Terran Supply Depot"},
    {110, "Terran Refinery"},
    {111, "Terran Barracks"},
    {112, "Terran Academy"},
    {113, "Terran Factory"},
    {114, "Terran Starport"},
    {115, "Terran Control Tower"},
    {116, "Terran Science Facility"},
    {117, "Terran Covert Ops"},
    {118, "Terran Physics Lab"},
    {119, "Starbase (Unused)"},
    {120, "Terran Machine Shop"},
    {121, "Repair Bay (Unused)"},
    {122, "Terran Engineering Bay"},
    {123, "Terran Armory"},
    {124, "Terran Missile Turret"},
    {125, "Terran Bunker"},
    {126, "Norad II (Crashed)"},
    {127, "Ion Cannon"},
    {128, "Uraj Crystal"},
    {129, "Khalis Crystal"},
    {130, "Infested Command Center"},
    {131, "Zerg Hatchery"},
    {132, "Zerg Lair"},
    {133, "Zerg Hive"},
    {134, "Zerg Nydus Canal"},
    {135, "Zerg Hydralisk Den"},
    {136, "Zerg Defiler Mound"},
    {137, "Zerg Greater Spire"},
    {138, "Zerg Queen's Nest"},
    {139, "Zerg Evolution Chamber"},
    {140, "Zerg Ultralisk Cavern"},
    {141, "Zerg Spire"},
    {142, "Zerg Spawning Pool"},
    {143, "Zerg Creep Colony"},
    {144, "Zerg Spore Colony"},
    {145, "Unused Zerg Building1"},
    {146, "Zerg Sunken Colony"},
    {147, "Zerg Overmind (With Shell)"},
    {148, "Zerg Overmind"},
    {149, "Zerg Extractor"},
    {150, "Mature Chrysalis"},
    {151, "Zerg Cerebrate"},
    {152, "Zerg Cerebrate Daggoth"},
    {153, "Unused Zerg Building2"},
    {154, "Protoss Nexus"},
    {155, "Protoss Robotics Facility"},
    {156, "Protoss Pylon"},
    {157, "Protoss Assimilator"},
    {158, "Unused Protoss Building1"},
    {159, "Protoss Observatory"},
    {160, "Protoss Gateway"},
    {161, "Unused Protoss Building2"},
    {162, "Protoss Photon Cannon"},
    {163, "Protoss Citadel of Adun"},
    {164, "Protoss Cybernetics Core"},
    {165, "Protoss Templar Archives"},
    {166, "Protoss Forge"},
    {167, "Protoss Stargate"},
    {168, "Stasis Cell/Prison"},
    {169, "Protoss Fleet Beacon"},
    {170, "Protoss Arbiter Tribunal"},
    {171, "Protoss Robotics Support Bay"},
    {172, "Protoss Shield Battery"},
    {173, "Khaydarin Crystal Formation"},
    {174, "Protoss Temple"},
    {175, "Xel'Naga Temple"},
    {176, "Mineral Field (Type 1)"},
    {177, "Mineral Field (Type 2)"},
    {178, "Mineral Field (Type 3)"},
    {179, "Cave (Unused)"},
    {180, "Cave-in (Unused)"},
    {181, "Cantina (Unused)"},
    {182, "Mining Platform (Unused)"},
    {183, "Independent Command Center (Unused)"},
    {184, "Independent Starport (Unused)"},
    {185, "Independent Jump Gate (Unused)"},
    {186, "Ruins (Unused)"},
    {187, "Khaydarin Crystal Formation (Unused)"},
    {188, "Vespene Geyser"},
    {189, "Warp Gate"},
    {190, "Psi Disrupter"},
    {191, "Zerg Marker"},
    {192, "Terran Marker"},
    {193, "Protoss Marker"},
    {194, "Zerg Beacon"},
    {195, "Terran Beacon"},
    {196, "Protoss Beacon"},
    {197, "Zerg Flag Beacon"},
    {198, "Terran Flag Beacon"},
    {199, "Protoss Flag Beacon"},
    {200, "Power Generator"},
    {201, "Overmind Cocoon"},
    {202, "Dark Swarm"},
    {203, "Floor Missile Trap"},
    {204, "Floor Hatch (Unused)"},
    {205, "Left Upper Level Door"},
    {206, "Right Upper Level Door"},
    {207, "Left Pit Door"},
    {208, "Right Pit Door"},
    {209, "Floor Gun Trap"},
    {210, "Left Wall Missile Trap"},
    {211, "Left Wall Flame Trap"},
    {212, "Right Wall Missile Trap"},
    {213, "Right Wall Flame Trap"},
    {214, "Start Location"},
    {215, "Flag"},
    {216, "Young Chrysalis"},
    {217, "Psi Emitter"},
    {218, "Data Disc"},
    {219, "Khaydarin Crystal"},
    {220, "Mineral Cluster Type 1"},
    {221, "Mineral Cluster Type 2"},
    {222, "Protoss Vespene Gas Orb Type 1"},
    {223, "Protoss Vespene Gas Orb Type 2"},
    {224, "Zerg Vespene Gas Sac Type 1"},
    {225, "Zerg Vespene Gas Sac Type 2"},
    {226, "Terran Vespene Gas Tank Type 1"},
    {227, "Terran Vespene Gas Tank Type 2"},
    {228, "Unused unit 228"},
    {229, "(any unit)"},
    {230, "(men)"},
    {231, "(buildings)"},
    {232, "(factories)"}
};
